# Formation energy prediction

> Requires the dev installation (see README): `uv pip install -e ".[dev]"`

The input to the model can be CIF files, POSCAR (use `input_format='vasp'`), PyMatGen Structures or ASE Atoms.

- **Example 1:** passing the CIF files directly to the model and getting the predictions.
- **Example 2:** creating the image generator first, to check which crystals are valid for the model and to get the predictions of all rotational ensembles.

In [1]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)  # pandas deprecation warnings

from xiespp import formation_energy, get_test_samples

model = formation_energy.FormationEnergyPredictor()  # device='/device:GPU:0' to use a GPU
model

## Example 1: CIF files → formation energy

In [2]:
cif_files = sorted(get_test_samples('MoS2'))
cif_files

['/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_12.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_136.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_14.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_141.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_194.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_33.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_61.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_62.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_74.cif']

In [3]:
# Formation energy (eV/atom) of each input file (NaN for crystals that do not meet the requirements of the model)
yp = model.predict(cif_files, verbose=0)
yp

0   -1.039229
1   -1.058999
2   -0.969547
3   -1.080808
4   -0.415095
5   -0.911958
6   -0.854338
7   -0.807296
8   -0.516125
Name: mean, dtype: float64

## Example 2: Using the image generator
The image generator reads the structures and prepares the CVR images once; it can then be passed to the model.

In [4]:
gen = formation_energy.prepare_data(
    data_input=cif_files,
    # input_format='vasp',  # Use this if the files are not CIF files
)

Reading CIF files...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 180.64it/s]

Preparing image objects...

Checking image requirements...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 3640.19it/s]

Valid images:       9 /       9

Preparing point clouds...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 3013.15it/s]

In [5]:
# Crystals that do not meet the requirements of the model are marked as not valid
gen.df[['file', 'is_valid']]

                                                file  is_valid
0  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
1  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
2  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
3  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
4  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
5  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
6  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
7  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
8  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True

In [6]:
yp = model.predict(gen, return_all_ensembles=True, verbose=0)

# Besides the final prediction (mean, eV/atom), the values of all the rotational ensembles are reported.
# Missing values are the crystals that did not meet the requirements of the model.
# If return_all_ensembles is False, only the mean value is returned.
yp

,mean,0,1,2,3,4,5,6,7,8,...,40,41,42,43,44,45,46,47,48,49
0,-1.053814,-0.987458,-1.139910,-1.081112,-1.115243,-1.021101,-1.054273,-1.070653,-1.072875,-1.023686,...,-1.041562,-1.024475,-1.005405,-1.279092,-1.050708,-1.145004,-0.945509,-0.989188,-1.019722,-1.194376
1,-1.065585,-1.122770,-1.066366,-1.030086,-0.980274,-1.098580,-1.054011,-0.922579,-1.057794,-1.148341,...,-1.108392,-1.024008,-1.037785,-1.021234,-1.024330,-1.002099,-1.153699,-1.007699,-1.114560,-1.077960
2,-0.961931,-1.083234,-0.914750,-0.969159,-0.979950,-0.853385,-0.877680,-0.927143,-0.976729,-0.990083,...,-1.023913,-0.942144,-0.966323,-1.048980,-0.995659,-0.954494,-0.883512,-0.901657,-0.978019,-1.084579
3,-1.083332,-0.815426,-1.182051,-0.962639,-1.032915,-1.286531,-0.877242,-1.068794,-1.009166,-1.050212,...,-1.094852,-1.100427,-1.066888,-1.198452,-1.049526,-1.057874,-1.145039,-1.090040,-1.039005,-1.233731
4,-0.406437,-0.310900,-0.417921,-0.433930,-0.439965,-0.593404,-0.321690,-0.361830,-0.370719,-0.354279,...,-0.382977,-0.431432,-0.381288,-0.394225,-0.407091,-0.412438,-0.376457,-0.393203,-0.500788,-0.360576
5,-0.911072,-0.897669,-0.932744,-0.988678,-0.826994,-0.880637,-0.892060,-0.898847,-0.949417,-0.974560,...,-1.026494,-1.013837,-0.911538,-0.919872,-0.885046,-0.915448,-0.859081,-0.894043,-0.857206,-0.893483
6,-0.862872,-0.849191,-0.754331,-0.770909,-0.762504,-0.893164,-0.790822,-0.983576,-0.807642,-0.994983,...,-0.919048,-0.958742,-0.743193,-0.797510,-0.863210,-0.926874,-0.734224,-1.038433,-1.226432,-0.840913
7,-0.798301,-0.817034,-0.837004,-0.859432,-0.709047,-0.806340,-0.718483,-0.892632,-0.760351,-0.726195,...,-0.777615,-0.851045,-0.774077,-0.892972,-0.829686,-0.862693,-0.883747,-0.591069,-0.796721,-0.595800
8,-0.523313,-0.456367,-0.499295,-0.549964,-0.497137,-0.555071,-0.625085,-0.499172,-0.499692,-0.521084,...,-0.461043,-0.543017,-0.592700,-0.540315,-0.563286,-0.623177,-0.574393,-0.548547,-0.643494,-0.572515

### (Optional) Structures from the Materials Project
PyMatGen structures can be used in the same way. Set the `MP_API_KEY` environment variable (or paste your key below) to run this cell.

In [7]:
import os

api_key = os.environ.get('MP_API_KEY')  # or: api_key = '__YOUR_API_KEY__'
if api_key:
    from mp_api.client import MPRester
    with MPRester(api_key) as mpr:
        docs = mpr.materials.summary.search(chemsys='Si-O', fields=['material_id', 'structure'])[:10]
    yp_mp = model.predict([d.structure for d in docs], verbose=0)
    yp_mp.index = [d.material_id for d in docs]
    display(yp_mp)
else:
    print('MP_API_KEY is not set: skipped.')

MP_API_KEY is not set: skipped.

## Command line usage
Run `xiespp formation-energy -h` for all options.

In [8]:
!xiespp formation-energy --test -o formation_energy.csv 2>/dev/null

file,formation_energy
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/GaN/GaN_12.cif,0.2490600550174713
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/GaN/GaN_9.cif,-0.5386525350809097